version: 2

builds:
  - main: .
    binary: swarm
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/matt/swarm-cli/internal/version.Version={{.Version}}
      - -X github.com/matt/swarm-cli/internal/version.Commit={{.ShortCommit}}
      - -X github.com/matt/swarm-cli/internal/version.BuildDate={{.Date}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ .ShortCommit }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

release:
  github:
    owner: matt
    name: swarm-cli
  draft: false
  prerelease: auto
