# Patchboard Validation Workflow
#
# Validates .patchboard/ task data on PRs and pushes.
# Installed automatically by the patchboard management plane during tooling install.
#
name: Patchboard Validation

on:
  pull_request:
  push:
    branches: ["main", "master"]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for comparing against base branch

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Validate .patchboard invariants
        run: |
          bash .patchboard/tooling/validate.sh --verbose

      - name: Validate PR title contains task ID (on PRs)
        if: github.event_name == 'pull_request'
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_BRANCH: ${{ github.head_ref }}
        run: |
          # Check if PR title or branch contains a task ID (T-XXXX pattern)
          if [[ "$PR_TITLE" =~ T-[0-9]{4} ]] || [[ "$PR_BRANCH" =~ T-[0-9]{4} ]]; then
            echo "Task ID found in PR title or branch name"
            # Extract task ID
            if [[ "$PR_TITLE" =~ (T-[0-9]{4}) ]]; then
              TASK_ID="${BASH_REMATCH[1]}"
            elif [[ "$PR_BRANCH" =~ (T-[0-9]{4}) ]]; then
              TASK_ID="${BASH_REMATCH[1]}"
            fi
            echo "  Task: $TASK_ID"

            # Verify task exists
            if [ -d ".patchboard/tasks/$TASK_ID" ]; then
              echo "Task $TASK_ID exists"
            else
              echo "Warning: Task $TASK_ID not found in .patchboard/tasks/"
              echo "  This may be intentional for non-task PRs"
            fi
          else
            echo "No task ID (T-XXXX) found in PR title or branch"
            echo "  Title: $PR_TITLE"
            echo "  Branch: $PR_BRANCH"
            echo ""
            echo "  For task-related PRs, include the task ID in the title or branch name"
            echo "  Example: 'T-0001: Implement feature' or branch 'T-0001-feature'"
          fi

      - name: Validate tasks are not being set to done (on PRs)
        if: github.event_name == 'pull_request'
        env:
          BASE_REF: ${{ github.event.pull_request.base.ref }}
        run: |
          echo "Checking for tasks being set to 'done' status..."

          # Get list of changed task files (T-XXXX and E-XXXX patterns)
          CHANGED_TASKS=$(git diff --name-only origin/${BASE_REF}...HEAD | grep -E "\.patchboard/tasks/(T|E)-[0-9]{4}/task\.md" || true)

          if [ -z "$CHANGED_TASKS" ]; then
            echo "No task files changed in this PR"
            exit 0
          fi

          ERRORS=0
          for TASK_FILE in $CHANGED_TASKS; do
            # Skip if file doesn't exist (deleted tasks)
            if [ ! -f "$TASK_FILE" ]; then
              echo "  $TASK_FILE was deleted, skipping"
              continue
            fi

            # Get old status from base branch (empty if new file)
            OLD_STATUS=$(git show origin/${BASE_REF}:"$TASK_FILE" 2>/dev/null | grep "^status:" | awk '{print $2}' || echo "")

            # Get new status from current branch
            NEW_STATUS=$(grep "^status:" "$TASK_FILE" | awk '{print $2}')

            echo "  Checking $TASK_FILE: $OLD_STATUS -> $NEW_STATUS"

            # Check if transitioning TO 'done' (and not already 'done')
            if [ "$NEW_STATUS" = "done" ] && [ "$OLD_STATUS" != "done" ]; then
              echo ""
              echo "ERROR: $TASK_FILE is being set to 'done' status"
              echo ""
              echo "   Tasks cannot be set to 'done' via PR."
              echo "   Set status to 'review' instead -- humans will mark as 'done' after approval."
              echo ""
              ERRORS=$((ERRORS + 1))
            fi
          done

          if [ $ERRORS -gt 0 ]; then
            echo ""
            echo "============================================"
            echo "VALIDATION FAILED: $ERRORS task(s) being set to 'done'"
            echo ""
            echo "Policy: Only humans can set tasks to 'done' status."
            echo "Agents should set tasks to 'review' when work is complete."
            echo "============================================"
            exit 1
          fi

          echo "No tasks being improperly set to 'done'"
